//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanceUmDesafio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public int IdComentario { get; set; }
        public string Conteudo { get; set; }
        public string IDUsuario { get; set; }
        public Nullable<System.DateTime> DataComentario { get; set; }
        public int IDDesafio { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Desafio Desafio { get; set; }
    }
}
