//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanceUmDesafio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desafio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Desafio()
        {
            this.Comentario = new HashSet<Comentario>();
        }
    
        public int IdDesafio { get; set; }
        public string Titulo { get; set; }
        public Nullable<double> Rank { get; set; }
        public string Conteudo { get; set; }
        public string IDUsuario { get; set; }
        public Nullable<int> IDCategoria { get; set; }
        public Nullable<System.DateTime> DataPostagem { get; set; }
        public string Dicas { get; set; }
        public Nullable<int> Votos { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comentario> Comentario { get; set; }
    }
}
